//ENV
const API_JOKE_BASE_URL = import.meta.env.VITE_API_JOKE_BASE_URL
const API_JOKES_TYPES_ROUTE = import.meta.env.VITE_API_JOKES_TYPES_ROUTE
const API_JOKES_RANDOM_JOKE_ROUTE = import.meta.env.VITE_API_JOKES_RANDOM_JOKE_ROUTE
const API_JOKES_RANDOM_TYPE_TEN_JOKE_ROUTE = import.meta.env
  .VITE_API_JOKES_RANDOM_TYPE_TEN_JOKE_ROUTE

//CONST
const KEYS = {
  type: ':type',
}
export {
  API_JOKE_BASE_URL,
  API_JOKES_TYPES_ROUTE,
  API_JOKES_RANDOM_JOKE_ROUTE,
  API_JOKES_RANDOM_TYPE_TEN_JOKE_ROUTE,
  KEYS,
}
